trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
    - npm

# Added these variables
variables:
  # Specifies the build configuration
  buildConfiguration: 'Release'
  # Specifies the path to the wwwroot directory
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  # Specifies the .NET Core SDK version to use
  dotnetSdkVersion: '3.1.300'

steps:
- task: UseDotNet@2
  # Use the variable dotnetSdkVersion
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    # Use the variable dotnetSdkVersion
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

# Use the variable wwwrootDir
- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  # Use the variable wwwrootDir
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  # Use the variable buildConfiguration
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    # Use the variable buildConfiguration
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

# To publish or package the application's build results (including it dependencies into a folder)
- task: DotNetCoreCLI@2
  # Use the variable
  displayName: 'Publish the project - $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    # Use the variable buildConfiguration
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    # This argument specifies to add the build results to a .zip file
    zipAfterPublish: true

# To publish the .zip file to Azure Pipelines
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  # This arcument specifies to run the task only when the previous task succeeds
  condition: succeeded()